version: 2
project_name: mcp-memory

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: unix
    main: ./cmd/mcp-memory
    binary: mcp-memory
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"
  - id: windows
    main: ./cmd/mcp-memory
    binary: mcp-memory
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: unix
    ids:
      - unix
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    files:
      - README.md
  - id: windows
    ids:
      - windows
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - zip
    files:
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: brbranch
    name: embedding_mcp
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
